distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.5.0
install_time: "Sun Apr  7 15:48:10 2024"
installation_id: "f8ff3343-41e9-4cf8-b7ae-7122ac559218"
rime_version: 1.7.3